replicaCount: 1
image:
  repository: peishu/paymentservice
  tag: f420642108bd7f5a7fe7f7850f79c4c5d5611048
  pullPolicy: IfNotPresent
nameOverride: ""
fullnameOverride: ""
service:
  type: ClusterIP
  port: 50051
resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
